//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountVisualizer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Trikkie\\\\_MAPPEN_\\\\Jonas\\\\Allerlei\\\\Surplas\\\\Financien\\\\AccountReport." +
            "csv")]
        public string SourceCsv {
            get {
                return ((string)(this["SourceCsv"]));
            }
            set {
                this["SourceCsv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\Users\Trikkie\_MAPPEN_\Jonas\Allerlei\Surplas\Financien\Facturen_Inkomend\Facturen\2015</string>
  <string>C:\Users\Trikkie\_MAPPEN_\Jonas\Allerlei\Surplas\Financien\Facturen_Inkomend\Facturen\2016</string>
  <string>C:\Users\Trikkie\_MAPPEN_\Jonas\Allerlei\Surplas\Financien\Facturen_Inkomend\Facturen\2017</string>
  <string>C:\Users\Trikkie\_MAPPEN_\Jonas\Allerlei\Surplas\Financien\Facturen_Inkomend\OnkostenNotas</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SourceFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SourceFolders"]));
            }
            set {
                this["SourceFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Trikkie\\\\Documents\\\\Visual Studio 2017\\\\Projects\\\\AccountAnalyser\\\\Acc" +
            "ountAnalyserTest\\\\TestData\\\\ExampleOverviewData.csv")]
        public string SourceCsvBackup {
            get {
                return ((string)(this["SourceCsvBackup"]));
            }
            set {
                this["SourceCsvBackup"] = value;
            }
        }
    }
}
